<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\Coupon;
use App\Models\Order;
use App\Models\OrderItem;
use App\Models\Review;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. USERS
        $admin = User::create([
            'name' => 'Quản Trị Viên BeeStyle',
            'email' => 'admin@beestyle.vn',
            'password' => Hash::make('password'),
            'role' => 'admin',
            'phone' => '0988888888',
            'address' => 'Tòa nhà BeeStyle Center, Cầu Giấy, Hà Nội',
            'status' => 'active',
            'points' => 0,
        ]);

        $staff = User::create([
            'name' => 'Nhân Viên Bán Hàng',
            'email' => 'staff@beestyle.vn',
            'password' => Hash::make('password'),
            'role' => 'admin',
            'phone' => '0977777777',
            'address' => 'Cửa hàng BeeStyle Flagship, Đống Đa, Hà Nội',
            'status' => 'active',
            'points' => 0,
        ]);

        $customer1 = User::create([
            'name' => 'Nguyễn Văn Hùng',
            'email' => 'hung.nguyen@gmail.com',
            'password' => Hash::make('password'),
            'role' => 'customer',
            'phone' => '0912345678',
            'address' => 'Số 18 Phố Huế, Hoàn Kiếm, Hà Nội',
            'status' => 'active',
            'points' => 1250,
        ]);

        $customer2 = User::create([
            'name' => 'Trần Minh Quang',
            'email' => 'quang.tran@gmail.com',
            'password' => Hash::make('password'),
            'role' => 'customer',
            'phone' => '0934567890',
            'address' => 'Toà Park 7 Times City, Hai Bà Trưng, Hà Nội',
            'status' => 'active',
            'points' => 480,
        ]);

        $customer3 = User::create([
            'name' => 'Lê Tuấn Anh',
            'email' => 'tuananh.le@gmail.com',
            'password' => Hash::make('password'),
            'role' => 'customer',
            'phone' => '0945678901',
            'address' => '45 Lê Duẩn, Quận 1, TP. Hồ Chí Minh',
            'status' => 'active',
            'points' => 890,
        ]);

        // 2. CATEGORIES (5 Danh Mục Áo Nam Chuyên Biệt + 1 BST Mới)
        $catPolo = Category::create([
            'name' => 'Áo Polo Nam',
            'slug' => 'ao-polo-nam',
            'icon' => 'fa-solid fa-shirt',
            'image' => '/assets/img/products/polo_01.jpg',
            'description' => 'Áo polo nam cotton dệt tổ ong, dệt pique thể thao, sợi bamboo kháng khuẩn, thoáng mát lịch lãm',
            'sort_order' => 1,
            'is_active' => true,
        ]);

        $catShirt = Category::create([
            'name' => 'Áo Sơ Mi Nam',
            'slug' => 'ao-so-mi-nam',
            'icon' => 'fa-solid fa-user-tie',
            'image' => '/assets/img/products/somi_02.jpg',
            'description' => 'Sơ mi trắng công sở, sơ mi bamboo kháng nhăn, sơ mi denim, sơ mi flannel caro và sơ mi lụa cao cấp',
            'sort_order' => 2,
            'is_active' => true,
        ]);

        $catTshirt = Category::create([
            'name' => 'Áo Phông & T-Shirt Nam',
            'slug' => 'ao-phong-tshirt-nam',
            'icon' => 'fa-solid fa-tshirt',
            'image' => '/assets/img/products/tshirt_01.jpg',
            'description' => 'Áo phông 100% cotton 250GSM dày dặn đứng phom, áo thun basic co giãn và graphic streetwear cá tính',
            'sort_order' => 3,
            'is_active' => true,
        ]);

        $catBlazer = Category::create([
            'name' => 'Áo Khoác & Blazer Nam',
            'slug' => 'ao-khoac-blazer-nam',
            'icon' => 'fa-solid fa-vest',
            'image' => '/assets/img/products/outerwear_01.jpg',
            'description' => 'Áo blazer phong cách Hàn Quốc, áo khoác biker jacket da thật, áo bomber gió và áo khoác dù thể thao',
            'sort_order' => 4,
            'is_active' => true,
        ]);

        $catSweater = Category::create([
            'name' => 'Áo Sweater & Nỉ Nam',
            'slug' => 'ao-sweater-ni-nam',
            'icon' => 'fa-solid fa-snowflake',
            'image' => '/assets/img/products/sweater_01.jpg',
            'description' => 'Áo sweater nỉ da cá cổ tròn, áo hoodie nỉ bông có mũ, áo len dệt kim và áo nỉ streetwear ấm áp',
            'sort_order' => 5,
            'is_active' => true,
        ]);

        $catCollection = Category::create([
            'name' => 'BST Áo Mới 2026',
            'slug' => 'bo-suu-tap-ao-moi',
            'icon' => 'fa-solid fa-fire',
            'image' => '/assets/img/products/somi_01.jpg',
            'description' => 'Bộ sưu tập áo nam thiết kế độc quyền mới nhất theo xu hướng Casual hiện đại',
            'sort_order' => 6,
            'is_active' => true,
        ]);

        // 3. 50 PRODUCTS (10 SẢN PHẨM / DANH MỤC - TÊN VÀ HÌNH ẢNH KHỚP 100% KHÔNG TRÙNG NHAU)
        $allProductsData = [
            // ==========================================
            // DANH MỤC 1: ÁO POLO NAM (10 Sản phẩm)
            // ==========================================
            [
                'category_id' => $catPolo->id,
                'sku' => 'BS-PL-001',
                'name' => 'Áo Polo Nam BeeStyle Premium Cotton Dệt Tổ Ong Kháng Khuẩn',
                'slug' => 'ao-polo-nam-beestyle-premium-cotton-det-to-ong',
                'price' => 389000,
                'original_price' => 499000,
                'stock' => 150,
                'sold_count' => 850,
                'rating' => 4.9,
                'reviews_count' => 128,
                'image' => '/assets/img/products/polo_01.jpg',
                'colors' => ['Xanh Slate', 'Xanh Mint', 'Cam San Hô', 'Xám Ghi'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Chất liệu 100% Cotton dệt tổ ong cao cấp, xử lý kháng khuẩn Ion Bạc, khử mùi vượt trội suốt ngày dài.',
                'description' => 'Áo Polo Nam BeeStyle Premium mang đến sự chỉn chu tuyệt đối cho quý ông hiện đại với cấu trúc dệt thoáng khí và giữ phom hoàn hảo.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catPolo->id,
                'sku' => 'BS-PL-002',
                'name' => 'Áo Polo Nam Thể Thao Dry-Tech Co Giãn 4 Chiều Siêu Thoáng Khí',
                'slug' => 'ao-polo-nam-the-thao-dry-tech-co-gian-4-chieu',
                'price' => 319000,
                'original_price' => 399000,
                'stock' => 180,
                'sold_count' => 610,
                'rating' => 4.8,
                'reviews_count' => 84,
                'image' => '/assets/img/products/polo_02.jpg',
                'colors' => ['Xanh Coban', 'Xám Đậm', 'Đen Classic'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Công nghệ Dry-Tech làm khô siêu tốc, co giãn 4 chiều vận động thoải mái tối đa.',
                'description' => 'Chiếc áo polo thể thao hoàn hảo cho các hoạt động thể thao ngoài trời golf, tennis hay dạo phố năng động.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catPolo->id,
                'sku' => 'BS-PL-003',
                'name' => 'Áo Polo Nam Trơn Regular Fit Sợi Cotton Compact Kháng Mùi',
                'slug' => 'ao-polo-nam-tron-regular-fit-cotton-compact',
                'price' => 329000,
                'original_price' => 420000,
                'stock' => 160,
                'sold_count' => 740,
                'rating' => 4.9,
                'reviews_count' => 112,
                'image' => '/assets/img/products/polo_03.jpg',
                'colors' => ['Trắng Sữa', 'Beige Cát', 'Xám Tro'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Sợi bông chải kỹ Cotton Compact siêu mịn, công nghệ xử lý bề mặt chống xù lông tuyệt đối.',
                'description' => 'Phong cách tối giản Minimalism dễ phối cùng mọi loại quần tây hay kaki.',
                'is_new' => false,
                'is_featured' => false,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catPolo->id,
                'sku' => 'BS-PL-004',
                'name' => 'Áo Polo Nam Classic White Pique Cổ Bẻ Dệt Bo Viền Tinh Tế',
                'slug' => 'ao-polo-nam-classic-white-pique-co-be-det-bo',
                'price' => 359000,
                'original_price' => 450000,
                'stock' => 140,
                'sold_count' => 490,
                'rating' => 4.8,
                'reviews_count' => 76,
                'image' => '/assets/img/products/polo_04.jpg',
                'colors' => ['Trắng Tinh Khôi', 'Trắng Kem'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Vải dệt cá sấu Pique định lượng 230GSM dày dặn, đứng phom cổ không quăn mép.',
                'description' => 'Mẫu áo polo trắng kinh điển mang đến vẻ ngoài sạch sẽ, đĩnh đạc và chuẩn mực cho phái mạnh.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catPolo->id,
                'sku' => 'BS-PL-005',
                'name' => 'Áo Polo Nam Phom Slimfit Tôn Dáng Vải Dệt Cá Sấu Xuất Khẩu',
                'slug' => 'ao-polo-nam-phom-slimfit-ton-dang-vai-ca-sau',
                'price' => 369000,
                'original_price' => 480000,
                'stock' => 120,
                'sold_count' => 530,
                'rating' => 4.9,
                'reviews_count' => 88,
                'image' => '/assets/img/products/polo_05.jpg',
                'colors' => ['Đen Huyền Bí', 'Xanh Than', 'Nâu Cafe'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Cắt may phom ôm nhẹ Slimfit tôn đường nét cơ bắp nam tính, bề mặt vải mượt mà êm ái.',
                'description' => 'Tự tin khẳng định phong cách phái mạnh trong các cuộc gặp đối tác hay hẹn hò.',
                'is_new' => false,
                'is_featured' => true,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catPolo->id,
                'sku' => 'BS-PL-006',
                'name' => 'Áo Polo Nam Màu Xanh Sage Dịu Mát Chất Sợi Tre Chống Tia UV',
                'slug' => 'ao-polo-nam-mau-xanh-sage-diu-mat-soi-tre',
                'price' => 379000,
                'original_price' => 490000,
                'stock' => 110,
                'sold_count' => 380,
                'rating' => 4.8,
                'reviews_count' => 54,
                'image' => '/assets/img/products/polo_06.jpg',
                'colors' => ['Xanh Sage', 'Xanh Rêu Nhạt', 'Xanh Bạc Hà'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Chất liệu sợi tre tự nhiên Bamboo mát lịm, khả năng cản tia UV bảo vệ làn da.',
                'description' => 'Gam màu xanh Sage dịu mát xu hướng mới, mang lại năng lượng tích cực và thư thái suốt ngày dài.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catPolo->id,
                'sku' => 'BS-PL-007',
                'name' => 'Áo Polo Nam Vintage Phối Cổ Khóa Kéo Zip Kim Loại Trẻ Trung',
                'slug' => 'ao-polo-nam-vintage-phoi-co-khoa-keo-zip',
                'price' => 399000,
                'original_price' => 520000,
                'stock' => 95,
                'sold_count' => 340,
                'rating' => 4.9,
                'reviews_count' => 62,
                'image' => '/assets/img/products/polo_07.jpg',
                'colors' => ['Xám Khói Cổ Zip', 'Đen Cổ Zip'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Khóa kéo kim loại ánh bạc thay cho hàng cúc truyền thống, tạo điểm nhấn cá tính độc đáo.',
                'description' => 'Thiết kế phá cách kết hợp nét cổ điển và hiện đại, giúp bạn nổi bật trong mọi sự kiện.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catPolo->id,
                'sku' => 'BS-PL-008',
                'name' => 'Áo Polo Nam Minimalist Xám Tro Vải Cotton Lạnh Không Nhăn',
                'slug' => 'ao-polo-nam-minimalist-xam-tro-cotton-lanh',
                'price' => 339000,
                'original_price' => 430000,
                'stock' => 135,
                'sold_count' => 470,
                'rating' => 4.7,
                'reviews_count' => 69,
                'image' => '/assets/img/products/polo_08.jpg',
                'colors' => ['Xám Tro', 'Xám Melange', 'Ghi Sáng'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Chất Cotton lạnh chống nhăn nhàu, luôn giữ phom thẳng thớm sau nhiều lần giặt máy.',
                'description' => 'Lựa chọn hàng đầu cho nam giới bận rộn cần sự nhanh chóng, tiện lợi và luôn chỉn chu.',
                'is_new' => false,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catPolo->id,
                'sku' => 'BS-PL-009',
                'name' => 'Áo Polo Nam Streetwear In Chữ Ngực Phong Cách Phóng Khoáng',
                'slug' => 'ao-polo-nam-streetwear-in-chu-nguc-phong-khoang',
                'price' => 349000,
                'original_price' => 460000,
                'stock' => 105,
                'sold_count' => 410,
                'rating' => 4.8,
                'reviews_count' => 58,
                'image' => '/assets/img/products/polo_09.jpg',
                'colors' => ['Đen In Chữ', 'Trắng In Chữ'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Họa tiết typo ngực dập nổi cao cấp, dáng áo suông nhẹ năng động chuẩn streetwear.',
                'description' => 'Thể hiện gu thời trang trẻ trung, phóng khoáng khi kết hợp cùng quần short hoặc jeans ống rộng.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catPolo->id,
                'sku' => 'BS-PL-010',
                'name' => 'Áo Polo Nam Urban Cool Nẹp Cổ Giấu Cúc Sang Trọng Quý Phái',
                'slug' => 'ao-polo-nam-urban-cool-nep-co-giau-cuc',
                'price' => 399000,
                'original_price' => 510000,
                'stock' => 90,
                'sold_count' => 320,
                'rating' => 4.9,
                'reviews_count' => 45,
                'image' => '/assets/img/products/polo_10.jpg',
                'colors' => ['Xanh Navy Đậm', 'Đen Tuyển', 'Rêu Olive'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Hàng cúc được giấu kín tinh tế sau nẹp áo, mang lại diện mạo liền mạch thanh lịch tuyệt đối.',
                'description' => 'Mẫu polo thiết kế theo tiêu chuẩn may đo cao cấp của các thương hiệu thời trang quốc tế.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => false,
            ],

            // ==========================================
            // DANH MỤC 2: ÁO SƠ MI NAM (10 Sản phẩm)
            // ==========================================
            [
                'category_id' => $catShirt->id,
                'sku' => 'BS-SH-001',
                'name' => 'Áo Sơ Mi Nam Công Sở Cao Cấp Dệt Nẹp Giấu Chỉ Chống Nhăn',
                'slug' => 'ao-so-mi-nam-cong-so-cao-cap-det-nep-giau-chi',
                'price' => 490000,
                'original_price' => 650000,
                'stock' => 120,
                'sold_count' => 920,
                'rating' => 5.0,
                'reviews_count' => 140,
                'image' => '/assets/img/products/somi_01.jpg',
                'colors' => ['Xanh Navy Sọc', 'Trắng Sữa', 'Đỏ Rượu Vang'],
                'sizes' => ['38', '39', '40', '41', '42'],
                'short_description' => 'Vải dệt công nghệ chống nhăn Easy-Care, cổ áo gia cố keo nhiệt của Đức giữ form sắc nét.',
                'description' => 'Lựa chọn số 1 cho các buổi họp quan trọng, ký kết hợp đồng hay môi trường văn phòng đòi hỏi sự chỉn chu cao độ.',
                'is_new' => false,
                'is_featured' => true,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catShirt->id,
                'sku' => 'BS-SH-002',
                'name' => 'Áo Sơ Mi Nam Trắng Công Sở Dài Tay Vải Sợi Tre Bamboo Kháng Nhăn',
                'slug' => 'ao-so-mi-nam-trang-cong-so-dai-tay-soi-tre',
                'price' => 450000,
                'original_price' => 590000,
                'stock' => 180,
                'sold_count' => 1150,
                'rating' => 4.9,
                'reviews_count' => 210,
                'image' => '/assets/img/products/somi_02.jpg',
                'colors' => ['Trắng Tinh Khôi', 'Trắng Sữa'],
                'sizes' => ['38', '39', '40', '41', '42'],
                'short_description' => 'Vải sợi tre tự nhiên Bamboo mềm mượt như lụa, chống nhăn tự nhiên, thấm hút mồ hôi gấp 3 lần cotton.',
                'description' => 'Chiếc áo sơ mi trắng công sở quốc dân đem lại sự tự tin, chuyên nghiệp tuyệt đối cho quý ông.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catShirt->id,
                'sku' => 'BS-SH-003',
                'name' => 'Áo Sơ Mi Nam Denim Chambray Cộc Tay Họa Tiết Tim Nhí Trẻ Trung',
                'slug' => 'ao-so-mi-nam-denim-chambray-coc-tay',
                'price' => 390000,
                'original_price' => 490000,
                'stock' => 90,
                'sold_count' => 430,
                'rating' => 4.8,
                'reviews_count' => 64,
                'image' => '/assets/img/products/somi_03.jpg',
                'colors' => ['Xanh Denim Họa Tiết', 'Xanh Indigo'],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'short_description' => 'Vải Denim Chambray mỏng nhẹ thoáng mát dệt họa tiết tim nhỏ tinh tế, phong cách Casual phóng khoáng.',
                'description' => 'Chiếc áo sơ mi cộc tay mang tinh thần tự do, trẻ trung, thích hợp cho những buổi dạo phố, du lịch cuối tuần.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catShirt->id,
                'sku' => 'BS-SH-004',
                'name' => 'Áo Sơ Mi Nam Kẻ Flannel Caro Dài Tay Phong Cách Casual Streetwear',
                'slug' => 'ao-so-mi-nam-ke-flannel-caro-dai-tay',
                'price' => 420000,
                'original_price' => 550000,
                'stock' => 80,
                'sold_count' => 460,
                'rating' => 4.8,
                'reviews_count' => 59,
                'image' => '/assets/img/products/somi_04.jpg',
                'colors' => ['Vàng Phối Đen Caro', 'Đỏ Rượu Caro'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Vải dạ dệt Flannel 100% Cotton chải bông bề mặt êm mềm, giữ ấm nhẹ và đậm chất phong trần nam tính.',
                'description' => 'Áo sơ mi Flannel khoác ngoài áo thun basic tạo nên outfit layer cực chất cho phái mạnh dạo phố hay đi phượt du lịch.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catShirt->id,
                'sku' => 'BS-SH-005',
                'name' => 'Áo Sơ Mi Nam Oxford Kẻ Sọc Xanh Dài Tay Dáng Suông Hiện Đại',
                'slug' => 'ao-so-mi-nam-oxford-ke-soc-xanh-dai-tay',
                'price' => 440000,
                'original_price' => 560000,
                'stock' => 115,
                'sold_count' => 510,
                'rating' => 4.9,
                'reviews_count' => 73,
                'image' => '/assets/img/products/somi_05.jpg',
                'colors' => ['Kẻ Sọc Xanh Dương', 'Kẻ Sọc Xám'],
                'sizes' => ['38', '39', '40', '41', '42'],
                'short_description' => 'Vải Oxford dệt sọc dọc thanh thoát, tạo cảm giác thân hình thon gọn và cao ráo hơn.',
                'description' => 'Mẫu sơ mi kẻ sọc mang phong cách Smart Casual châu Âu, dễ dàng biến tấu từ công sở sang dạo phố.',
                'is_new' => false,
                'is_featured' => false,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catShirt->id,
                'sku' => 'BS-SH-006',
                'name' => 'Áo Sơ Mi Nam Lụa Dệt Ombre Pastel Phong Cách Nghệ Thuật Độc Đáo',
                'slug' => 'ao-so-mi-nam-lua-det-ombre-pastel',
                'price' => 480000,
                'original_price' => 620000,
                'stock' => 65,
                'sold_count' => 290,
                'rating' => 4.9,
                'reviews_count' => 42,
                'image' => '/assets/img/products/somi_06.jpg',
                'colors' => ['Xanh Dương Ombre', 'Cam San Hô Ombre', 'Xanh Ngọc Ombre'],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'short_description' => 'Hiệu ứng chuyển màu Ombre thủ công nghệ thuật, vải lụa tơ tằm nhân tạo bóng mờ óng ả.',
                'description' => 'Mẫu sơ mi mang vẻ đẹp thời thượng, phóng khoáng dành cho các buổi tiệc biển, sự kiện thời trang hoặc hẹn hò lãng mạn.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catShirt->id,
                'sku' => 'BS-SH-007',
                'name' => 'Áo Sơ Mi Nam Vải Đũi Linen Cổ Tàu Thoáng Mát Đi Biển & Dạo Phố',
                'slug' => 'ao-so-mi-nam-vai-dui-linen-co-tau',
                'price' => 410000,
                'original_price' => 530000,
                'stock' => 100,
                'sold_count' => 370,
                'rating' => 4.8,
                'reviews_count' => 51,
                'image' => '/assets/img/products/somi_07.jpg',
                'colors' => ['Trắng Linen', 'Beige Đũi', 'Xanh Nhạt'],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'short_description' => 'Chất đũi Linen tự nhiên thoáng khí mộc mạc, thiết kế cổ tàu trụ hiện đại không gò bó.',
                'description' => 'Tận hưởng cảm giác thư thái tuyệt đối trong những chuyến nghỉ dưỡng biển hay cà phê cuối tuần cùng bạn bè.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catShirt->id,
                'sku' => 'BS-SH-008',
                'name' => 'Áo Sơ Mi Nam May Đo May Sẵn Dáng Slimfit Đứng Form Chuẩn Quý Ông',
                'slug' => 'ao-so-mi-nam-may-do-dang-slimfit-chuan-quy-ong',
                'price' => 470000,
                'original_price' => 610000,
                'stock' => 130,
                'sold_count' => 580,
                'rating' => 4.9,
                'reviews_count' => 85,
                'image' => '/assets/img/products/somi_08.jpg',
                'colors' => ['Trắng Classic', 'Xanh Sky Blue', 'Hồng Pastel'],
                'sizes' => ['38', '39', '40', '41', '42'],
                'short_description' => 'Form áo may theo tỉ lệ chuẩn hình thể nam giới Việt Nam, đường may cuộn mép 5 mũi/cm tinh xảo.',
                'description' => 'Tạo nên phong thái đĩnh đạc, nam tính và đầy uy lực khi diện cùng quần tây hoặc suit.',
                'is_new' => false,
                'is_featured' => true,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catShirt->id,
                'sku' => 'BS-SH-009',
                'name' => 'Áo Sơ Mi Nam Xanh Pastel Công Sở Cổ Bẻ Ép Keo Đức Không Phồng Rộp',
                'slug' => 'ao-so-mi-nam-xanh-pastel-cong-so-co-be',
                'price' => 460000,
                'original_price' => 580000,
                'stock' => 145,
                'sold_count' => 620,
                'rating' => 4.8,
                'reviews_count' => 92,
                'image' => '/assets/img/products/somi_09.jpg',
                'colors' => ['Xanh Pastel Nhạt', 'Xanh Bạc Hà'],
                'sizes' => ['38', '39', '40', '41', '42'],
                'short_description' => 'Gam màu pastel trang nhã, công nghệ ép keo cổ và măng sét độc quyền không bao giờ bị rộp sau giặt.',
                'description' => 'Thổi làn gió mới vào tủ đồ công sở với sắc xanh tươi mát, xua tan căng thẳng nơi văn phòng làm việc.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catShirt->id,
                'sku' => 'BS-SH-010',
                'name' => 'Áo Sơ Mi Nam Đen Lịch Lãm Dạ Tiệc Dệt Gân Chìm Sang Trọng',
                'slug' => 'ao-so-mi-nam-den-lich-lam-da-tiec-det-gan-chim',
                'price' => 499000,
                'original_price' => 680000,
                'stock' => 85,
                'sold_count' => 390,
                'rating' => 4.9,
                'reviews_count' => 67,
                'image' => '/assets/img/products/somi_10.jpg',
                'colors' => ['Đen Tuyển Gân Chìm', 'Đen Ánh Tím'],
                'sizes' => ['38', '39', '40', '41', '42'],
                'short_description' => 'Vải dệt Jacquard gân chìm tinh vi, cúc áo đính ngọc trai đen cao cấp lấp lánh sang trọng.',
                'description' => 'Được thiết kế riêng cho những buổi dạ tiệc tối, sự kiện thảm đỏ hoặc gặp gỡ đối tác cấp cao.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => false,
            ],

            // ==========================================
            // DANH MỤC 3: ÁO PHÔNG & T-SHIRT NAM (10 Sản phẩm)
            // ==========================================
            [
                'category_id' => $catTshirt->id,
                'sku' => 'BS-TS-001',
                'name' => 'Áo Phông Nam Cổ Tròn Cotton 100% 250GSM Dày Dặn Phom Boxy',
                'slug' => 'ao-phong-nam-co-tron-cotton-250gsm-boxy',
                'price' => 249000,
                'original_price' => 320000,
                'stock' => 200,
                'sold_count' => 1420,
                'rating' => 4.9,
                'reviews_count' => 310,
                'image' => '/assets/img/products/tshirt_01.jpg',
                'colors' => ['Đen In Chữ', 'Trắng Basic', 'Xám Khói'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Vải Cotton 100% định lượng cao 250GSM dày dặn, không bai dão, phom Boxy trendy cá tính.',
                'description' => 'Item basic không thể thiếu trong tủ đồ hàng ngày, dễ dàng phối đồ với quần túi hộp, jeans hay short.',
                'is_new' => false,
                'is_featured' => true,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catTshirt->id,
                'sku' => 'BS-TS-002',
                'name' => 'Áo Thun Nam Trơn Trắng Cotton Compact 4 Chiều Thoáng Khí',
                'slug' => 'ao-thun-nam-tron-trang-cotton-compact',
                'price' => 219000,
                'original_price' => 280000,
                'stock' => 250,
                'sold_count' => 1890,
                'rating' => 4.8,
                'reviews_count' => 420,
                'image' => '/assets/img/products/tshirt_02.jpg',
                'colors' => ['Trắng Tinh Khôi', 'Đen Tuyển', 'Ghi Sáng'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Chất cotton compact co giãn 4 chiều siêu nhẹ, thoáng mát tột đỉnh cho những ngày nắng nóng.',
                'description' => 'Thích hợp làm áo lót trong sơ mi, mặc nhà hay tập gym, dạo phố hàng ngày.',
                'is_new' => false,
                'is_featured' => false,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catTshirt->id,
                'sku' => 'BS-TS-003',
                'name' => 'Áo Phông Nam Graphic Streetwear Họa Tiết Mèo Chiêu Tài May Mắn',
                'slug' => 'ao-phong-nam-graphic-streetwear-meo-chieu-tai',
                'price' => 269000,
                'original_price' => 350000,
                'stock' => 140,
                'sold_count' => 670,
                'rating' => 4.9,
                'reviews_count' => 95,
                'image' => '/assets/img/products/tshirt_03.jpg',
                'colors' => ['Beige Cát In Xanh', 'Trắng In Xanh'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Họa tiết in lụa cao su sắc nét không bong tróc, chất Cotton 100% thấm hút mồ hôi tối đa.',
                'description' => 'Áo phông Graphic BeeStyle với điểm nhấn họa tiết mèo chiêu tài cách điệu, mang lại may mắn và vẻ ngoài cá tính, năng động.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catTshirt->id,
                'sku' => 'BS-TS-004',
                'name' => 'Áo Phông Nam In Logo Vòng Tròn 705 Phong Cách Minimalist Street',
                'slug' => 'ao-phong-nam-in-logo-vong-tron-705',
                'price' => 259000,
                'original_price' => 330000,
                'stock' => 115,
                'sold_count' => 540,
                'rating' => 4.9,
                'reviews_count' => 77,
                'image' => '/assets/img/products/tshirt_04.jpg',
                'colors' => ['Đen Logo Trắng', 'Trắng Logo Đen'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Điểm nhấn logo tròn dập nổi ngực trái sắc nét, chất vải Cotton chải mượt mà mát rượi.',
                'description' => 'Sự hòa quyện giữa tinh thần đường phố năng động và thiết kế tối giản, dễ dàng kết hợp cùng quần short hay jeans cá tính.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catTshirt->id,
                'sku' => 'BS-TS-005',
                'name' => 'Áo Thun Nam Cổ Tròn Basic Cotton Heavyweight Phom Rộng Thoải Mái',
                'slug' => 'ao-thun-nam-co-tron-cotton-heavyweight',
                'price' => 229000,
                'original_price' => 299000,
                'stock' => 190,
                'sold_count' => 820,
                'rating' => 4.8,
                'reviews_count' => 110,
                'image' => '/assets/img/products/tshirt_05.jpg',
                'colors' => ['Trắng Tinh', 'Đen Basic', 'Xám Chuột'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Vải Heavyweight Cotton 220GSM chuẩn định lượng xuất khẩu, phom suông rộng thoải mái mọi vóc dáng.',
                'description' => 'Chiếc áo thun trơn quốc dân mà bất kỳ chàng trai nào cũng cần sở hữu, bền bỉ qua năm tháng không lo biến dạng cổ áo.',
                'is_new' => false,
                'is_featured' => false,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catTshirt->id,
                'sku' => 'BS-TS-006',
                'name' => 'Áo Phông Nam Trơn Màu Xám Tiêu Cotton Dệt Sợi Tự Nhiên Êm Ái',
                'slug' => 'ao-phong-nam-tron-mau-xam-tieu-cotton',
                'price' => 239000,
                'original_price' => 310000,
                'stock' => 160,
                'sold_count' => 590,
                'rating' => 4.8,
                'reviews_count' => 74,
                'image' => '/assets/img/products/tshirt_06.jpg',
                'colors' => ['Xám Tiêu Melange', 'Ghi Sáng'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Hiệu ứng dệt sợi tiêu đan xen bắt mắt, công nghệ chải xơ bông làm mềm tự nhiên không kích ứng.',
                'description' => 'Tông màu xám tiêu trung tính cực kỳ nịnh da, mang lại cảm giác dễ chịu và mộc mạc cho người mặc.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catTshirt->id,
                'sku' => 'BS-TS-007',
                'name' => 'Áo Phông Nam Vintage Washed Hiệu Ứng Bụi Bặm Đường Phố Retro',
                'slug' => 'ao-phong-nam-vintage-washed-bui-bam',
                'price' => 279000,
                'original_price' => 360000,
                'stock' => 105,
                'sold_count' => 480,
                'rating' => 4.9,
                'reviews_count' => 68,
                'image' => '/assets/img/products/tshirt_07.jpg',
                'colors' => ['Xám Khói Washed', 'Rêu Rửa Màu'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Xử lý giặt enzyme đá mài Vintage Wash tạo vệt loang cá tính độc bản không chiếc nào giống chiếc nào.',
                'description' => 'Phong cách hoài niệm thập niên 90s dành cho các tín đồ đam mê thời trang Retro và Y2K.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catTshirt->id,
                'sku' => 'BS-TS-008',
                'name' => 'Áo Thun Nam Oversize Cổ Tròn Phối Tag Da Góc Áo Tinh Tế',
                'slug' => 'ao-thun-nam-oversize-co-tron-tag-da',
                'price' => 249000,
                'original_price' => 330000,
                'stock' => 140,
                'sold_count' => 610,
                'rating' => 4.8,
                'reviews_count' => 83,
                'image' => '/assets/img/products/tshirt_08.jpg',
                'colors' => ['Xanh Rêu Sage', 'Beige Cát', 'Đen Tuyển'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Form áo rộng rãi che khuyết điểm bụng hoàn hảo, đính tag da bò dập chìm logo thương hiệu ở gấu áo.',
                'description' => 'Sự đơn giản đỉnh cao với những chi tiết gia công tỉ mỉ, tôn lên gu ăn mặc tinh tế của bạn.',
                'is_new' => false,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catTshirt->id,
                'sku' => 'BS-TS-009',
                'name' => 'Áo Phông Nam In Chữ Typography Nghệ Thuật Chất Lượng Cao',
                'slug' => 'ao-phong-nam-in-chu-typography-nghe-thuat',
                'price' => 259000,
                'original_price' => 340000,
                'stock' => 125,
                'sold_count' => 520,
                'rating' => 4.9,
                'reviews_count' => 71,
                'image' => '/assets/img/products/tshirt_09.jpg',
                'colors' => ['Trắng Typo Đen', 'Đen Typo Trắng'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Bố cục chữ nghệ thuật Typography truyền cảm hứng sống tích cực, công nghệ in nhiệt chìm không cộm ngứa.',
                'description' => 'Khẳng định cá tính tự tin, năng động trong mọi khoảnh khắc giao lưu bạn bè hay tham gia sự kiện ngoài trời.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catTshirt->id,
                'sku' => 'BS-TS-010',
                'name' => 'Áo Thun Nam Cộc Tay Raglan Phối Màu Tương Phản Thể Thao Năng Động',
                'slug' => 'ao-thun-nam-coc-tay-raglan-phoi-mau',
                'price' => 239000,
                'original_price' => 310000,
                'stock' => 150,
                'sold_count' => 640,
                'rating' => 4.8,
                'reviews_count' => 86,
                'image' => '/assets/img/products/tshirt_10.jpg',
                'colors' => ['Thân Trắng Tay Đen', 'Thân Xám Tay Xanh Than'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'short_description' => 'Cắt tay chéo Raglan đặc trưng của văn hóa bóng chày Mỹ, giúp bờ vai trông rộng và vạm vỡ hơn.',
                'description' => 'Mang đến diện mạo thể thao khỏe khoắn, tươi mới và tràn đầy sức sống tuổi trẻ.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => true,
            ],

            // ==========================================
            // DANH MỤC 4: ÁO KHOÁC & BLAZER NAM (10 Sản phẩm)
            // ==========================================
            [
                'category_id' => $catBlazer->id,
                'sku' => 'BS-BLZ-001',
                'name' => 'Áo Blazer Nam Kẻ Ca-rô Phong Cách Hàn Quốc Suông Rộng Minimalist',
                'slug' => 'ao-blazer-nam-ke-ca-ro-phong-cach-han-quoc',
                'price' => 890000,
                'original_price' => 1190000,
                'stock' => 60,
                'sold_count' => 380,
                'rating' => 4.9,
                'reviews_count' => 78,
                'image' => '/assets/img/products/outerwear_01.jpg',
                'colors' => ['Xanh Kẻ Ca-rô', 'Xám Tro', 'Nâu Cafe'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Chất vải tuyết mưa cao cấp 2 lớp chống nhăn, đệm vai nhẹ tự nhiên tôn dáng phái mạnh.',
                'description' => 'Thiết kế suông rộng thời thượng, cực kỳ dễ phối cùng áo thun trơn bên trong hoặc sơ mi cổ bẻ.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catBlazer->id,
                'sku' => 'BS-BLZ-002',
                'name' => 'Áo Blazer Nam Đen Công Sở 2 Lớp Đứng Dáng Đệm Vai Tự Nhiên',
                'slug' => 'ao-blazer-nam-den-cong-so-2-lop',
                'price' => 950000,
                'original_price' => 1250000,
                'stock' => 50,
                'sold_count' => 420,
                'rating' => 5.0,
                'reviews_count' => 92,
                'image' => '/assets/img/products/outerwear_02.jpg',
                'colors' => ['Đen Lịch Lãm', 'Xanh Navy Đậm'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Áo blazer đen công sở chuẩn may đo cao cấp, lót lụa habutai êm ái thoáng nhiệt.',
                'description' => 'Trang phục chuẩn mực cho các quý ông tham dự hội nghị, đàm phán hoặc sự kiện trang trọng.',
                'is_new' => false,
                'is_featured' => true,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catBlazer->id,
                'sku' => 'BS-JKT-003',
                'name' => 'Áo Khoác Da Nam Biker Jacket Da Bò Thật Khóa Kéo Bạc YKK',
                'slug' => 'ao-khoac-da-nam-biker-jacket-da-that',
                'price' => 1250000,
                'original_price' => 1650000,
                'stock' => 35,
                'sold_count' => 290,
                'rating' => 5.0,
                'reviews_count' => 64,
                'image' => '/assets/img/products/outerwear_03.jpg',
                'colors' => ['Đen Biker Cao Cấp'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Da bò nhập khẩu xử lý thuộc thảo mộc mềm mại, phụ kiện khóa kéo hợp kim YKK sáng bóng chống gỉ sét.',
                'description' => 'Biểu tượng phong trần, nam tính bất hủ dành cho các chàng trai đam mê phong cách Biker cá tính.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catBlazer->id,
                'sku' => 'BS-JKT-004',
                'name' => 'Áo Khoác Gió Bomber Nam Phối Khóa Kéo Thể Thao BeeStyle Air',
                'slug' => 'ao-khoac-gio-bomber-nam-the-thao-beestyle-air',
                'price' => 490000,
                'original_price' => 650000,
                'stock' => 95,
                'sold_count' => 480,
                'rating' => 4.8,
                'reviews_count' => 72,
                'image' => '/assets/img/products/outerwear_04.jpg',
                'colors' => ['Rêu Khaki', 'Đen Tuyển', 'Xanh Rêu Đậm'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Vải gió dù 2 lớp trượt nước chống gió lạnh, bo cổ và bo gấu dệt rib co giãn thể thao bền đẹp.',
                'description' => 'Mẫu áo khoác Bomber siêu nhẹ tiện lợi khi đi xe máy ngoài đường, cản gió giữ ấm và chống mưa phùn hiệu quả.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catBlazer->id,
                'sku' => 'BS-JKT-005',
                'name' => 'Áo Khoác Dù 2 Lớp Trượt Nước Chống Gió Bụi Đi Phượt Tiện Lợi',
                'slug' => 'ao-khoac-du-2-lop-truot-nuoc-chong-gio',
                'price' => 430000,
                'original_price' => 580000,
                'stock' => 110,
                'sold_count' => 530,
                'rating' => 4.8,
                'reviews_count' => 79,
                'image' => '/assets/img/products/outerwear_05.jpg',
                'colors' => ['Xanh Than Phối Ghi', 'Đen Phối Cam'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Công nghệ phủ màng Nano chống thấm nước cấp 4, mũ trùm đầu có thể tháo rời linh hoạt.',
                'description' => 'Bạn đồng hành tin cậy trên mọi cung đường phượt hay di chuyển thường ngày trong điều kiện thời tiết thất thường.',
                'is_new' => false,
                'is_featured' => false,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catBlazer->id,
                'sku' => 'BS-BLZ-006',
                'name' => 'Áo Blazer Nam Chất Vải Đũi Linen Mùa Hè Thoáng Nhẹ Phóng Khoáng',
                'slug' => 'ao-blazer-nam-chat-vai-dui-linen-mua-he',
                'price' => 790000,
                'original_price' => 1050000,
                'stock' => 70,
                'sold_count' => 310,
                'rating' => 4.9,
                'reviews_count' => 52,
                'image' => '/assets/img/products/outerwear_06.jpg',
                'colors' => ['Beige Cát Linen', 'Trắng Ngà'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Vải Linen mỏng nhẹ không lót lưng thoát nhiệt tối đa, mang lại sự dễ chịu ngay cả trong ngày hè oi bức.',
                'description' => 'Tạo nên diện mạo phóng khoáng phong cách quý ông Địa Trung Hải trong các kỳ nghỉ dưỡng biển.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catBlazer->id,
                'sku' => 'BS-BLZ-007',
                'name' => 'Áo Blazer Nam Dạ Tweed Dày Dặn Sang Trọng Mùa Thu Đông',
                'slug' => 'ao-blazer-nam-da-tweed-day-dan-thu-dong',
                'price' => 990000,
                'original_price' => 1350000,
                'stock' => 45,
                'sold_count' => 260,
                'rating' => 5.0,
                'reviews_count' => 48,
                'image' => '/assets/img/products/outerwear_07.jpg',
                'colors' => ['Xám Tro Tweed', 'Nâu Đất Tweed'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Chất dạ dệt Tweed len xơ thô cao cấp phong cách quý tộc Anh Quốc, giữ ấm thân nhiệt vượt trội.',
                'description' => 'Nâng tầm phong cách thời trang thu đông với vẻ đẹp cổ điển, sang trọng và đầy cuốn hút.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catBlazer->id,
                'sku' => 'BS-JKT-008',
                'name' => 'Áo Khoác Măng Tô Nam Dáng Dài Chất Dạ Ép Cao Cấp Quý Tộc',
                'slug' => 'ao-khoac-mang-to-nam-dang-dai-da-ep',
                'price' => 1450000,
                'original_price' => 1890000,
                'stock' => 30,
                'sold_count' => 180,
                'rating' => 4.9,
                'reviews_count' => 39,
                'image' => '/assets/img/products/outerwear_08.jpg',
                'colors' => ['Nâu Lạc Đà Camel', 'Đen Quý Phái'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Dạ ép lông cừu 2 mặt dày dặn, chiều dài qua gối tôn dáng chuẩn vóc mẫu nam Hàn Quốc.',
                'description' => 'Trang phục giữ ấm đẳng cấp nhất cho mùa đông giá lạnh, biến bạn thành tâm điểm thu hút mọi ánh nhìn.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catBlazer->id,
                'sku' => 'BS-JKT-009',
                'name' => 'Áo Khoác Jean Nam Denim Trucker Jacket Xanh Bụi Cổ Điển',
                'slug' => 'ao-khoac-jean-nam-denim-trucker-jacket',
                'price' => 590000,
                'original_price' => 790000,
                'stock' => 85,
                'sold_count' => 440,
                'rating' => 4.8,
                'reviews_count' => 67,
                'image' => '/assets/img/products/outerwear_09.jpg',
                'colors' => ['Xanh Bụi Rửa Sáng', 'Xanh Chàm Indigo'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Vải Denim 13oz bền bỉ đanh chắc, túi hộp ngực đôi phối cúc kim loại dập nổi thương hiệu.',
                'description' => 'Món đồ kinh điển của phong cách thời trang đường phố, càng mặc càng lên màu thời gian đẹp mắt.',
                'is_new' => false,
                'is_featured' => false,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catBlazer->id,
                'sku' => 'BS-JKT-010',
                'name' => 'Áo Khoác Cardigan Nam Dệt Kim Cổ Tim Cúc Cài Phong Cách Nhẹ Nhàng',
                'slug' => 'ao-khoac-cardigan-nam-det-kim-co-tim',
                'price' => 490000,
                'original_price' => 640000,
                'stock' => 90,
                'sold_count' => 360,
                'rating' => 4.9,
                'reviews_count' => 55,
                'image' => '/assets/img/products/outerwear_10.jpg',
                'colors' => ['Kem Sữa', 'Xám Tro', 'Xanh Navy'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Len dệt mịn màng nhẹ nhàng, hàng cúc cài sừng phong cách thư sinh lãng tử.',
                'description' => 'Rất thích hợp cho tiết trời se lạnh đầu thu hoặc làm việc trong môi trường máy lạnh điều hòa văn phòng.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],

            // ==========================================
            // DANH MỤC 5: ÁO SWEATER & NỈ NAM (10 Sản phẩm)
            // ==========================================
            [
                'category_id' => $catSweater->id,
                'sku' => 'BS-SW-001',
                'name' => 'Áo Sweater Nam Cổ Tròn Nỉ Da Cá Form Rộng Thu Đông Trắng Kem',
                'slug' => 'ao-sweater-nam-co-tron-ni-da-ca',
                'price' => 350000,
                'original_price' => 450000,
                'stock' => 150,
                'sold_count' => 780,
                'rating' => 4.9,
                'reviews_count' => 115,
                'image' => '/assets/img/products/sweater_01.jpg',
                'colors' => ['Trắng Kem', 'Xám Melange', 'Đen'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Chất liệu nỉ da cá 100% cotton dày dặn, dệt vòng sợi mềm mại, giữ ấm tốt và không xù lông.',
                'description' => 'Chiếc áo sweater hoàn hảo cho mùa thu đông với kiểu dáng tối giản, dễ dàng mix-match cùng quần jeans hoặc quần âu.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catSweater->id,
                'sku' => 'BS-SW-002',
                'name' => 'Áo Nỉ Nam Dài Tay Dáng Rộng Phong Cách Streetwear Cool BeeStyle',
                'slug' => 'ao-ni-nam-dai-tay-dang-rong-streetwear',
                'price' => 380000,
                'original_price' => 490000,
                'stock' => 110,
                'sold_count' => 540,
                'rating' => 4.8,
                'reviews_count' => 88,
                'image' => '/assets/img/products/sweater_02.jpg',
                'colors' => ['Đen Phối Tag Vàng', 'Xám Tro'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Form áo thụng phong cách hiphop cá tính, phối viền dệt rib co giãn ở cổ tay và gấu áo.',
                'description' => 'Thiết kế trẻ trung, năng động dành riêng cho giới trẻ yêu thích sự tự do và nổi bật.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catSweater->id,
                'sku' => 'BS-HD-003',
                'name' => 'Áo Hoodie Nam Nỉ Bông Có Mũ Dây Rút Giữ Ấm Mùa Đông Dày Dặn',
                'slug' => 'ao-hoodie-nam-ni-bong-co-mu-day-rut',
                'price' => 390000,
                'original_price' => 520000,
                'stock' => 110,
                'sold_count' => 680,
                'rating' => 4.9,
                'reviews_count' => 98,
                'image' => '/assets/img/products/sweater_03.jpg',
                'colors' => ['Xám Khói', 'Đen Basic', 'Xanh Than'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Chất nỉ bông dày dặn ấm áp 350GSM, mũ 2 lớp đứng phom và túi kangaroo phía trước tiện lợi.',
                'description' => 'Chiếc áo Hoodie không thể thiếu khi trời chuyển lạnh. Phom dáng Oversize trẻ trung đậm chất Gen Z thời thượng.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catSweater->id,
                'sku' => 'BS-HD-004',
                'name' => 'Áo Hoodie Nam Trơn Oversize Form Rộng Phong Cách Hàn Quốc',
                'slug' => 'ao-hoodie-nam-tron-oversize-han-quoc',
                'price' => 399000,
                'original_price' => 530000,
                'stock' => 125,
                'sold_count' => 590,
                'rating' => 4.8,
                'reviews_count' => 84,
                'image' => '/assets/img/products/sweater_04.jpg',
                'colors' => ['Beige Kem', 'Nâu Mocha', 'Đen Tuyển'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Chất nỉ chân cua mịn màng, mũ trùm bản rộng dây dù luồn kim loại chắc chắn.',
                'description' => 'Outfit chuẩn style Oppa Hàn Quốc khi kết hợp cùng quần suông rộng và giày sneaker trắng.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catSweater->id,
                'sku' => 'BS-SW-005',
                'name' => 'Áo Len Nam Dệt Kim Cổ Tròn Họa Tiết Vặn Thừng Vintage Classic',
                'slug' => 'ao-len-nam-det-kim-co-tron-van-thung',
                'price' => 420000,
                'original_price' => 560000,
                'stock' => 70,
                'sold_count' => 310,
                'rating' => 4.8,
                'reviews_count' => 51,
                'image' => '/assets/img/products/sweater_05.jpg',
                'colors' => ['Trắng Kem Vặn Thừng', 'Beige Nhạt'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Len lông cừu tổng hợp dệt vặn thừng 3D cổ điển, không ngứa, không châm chích da.',
                'description' => 'Thiết kế vintage quý phái theo phong cách quý ông cổ điển, dễ dàng phối cùng sơ mi trắng cổ bẻ bên trong.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catSweater->id,
                'sku' => 'BS-SW-006',
                'name' => 'Áo Len Nam Cổ Lọ Cao 3 Phân Giữ Ấm Cổ Mùa Đông Ấm Áp',
                'slug' => 'ao-len-nam-co-lo-cao-3-phan',
                'price' => 430000,
                'original_price' => 570000,
                'stock' => 80,
                'sold_count' => 420,
                'rating' => 4.9,
                'reviews_count' => 63,
                'image' => '/assets/img/products/sweater_06.jpg',
                'colors' => ['Đen Classic', 'Xám Tro', 'Nâu Rêu'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Dệt kim cổ lọ 3 phân ôm khít giữ ấm cổ họng tuyệt đối mà không gây cảm giác gò bó khó thở.',
                'description' => 'Công thức phối đồ hoàn hảo khi mặc bên trong áo blazer hoặc trench coat trong mùa đông giá rét.',
                'is_new' => false,
                'is_featured' => true,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catSweater->id,
                'sku' => 'BS-SW-007',
                'name' => 'Áo Sweater Nam Phối Màu Color Block Trẻ Trung Năng Động',
                'slug' => 'ao-sweater-nam-phoi-mau-color-block',
                'price' => 370000,
                'original_price' => 480000,
                'stock' => 95,
                'sold_count' => 390,
                'rating' => 4.8,
                'reviews_count' => 56,
                'image' => '/assets/img/products/sweater_07.jpg',
                'colors' => ['Phối Trắng Xanh Cam', 'Phối Đen Xám Be'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Các mảng màu tương phản được ghép nối hình học tinh tế, vải nỉ bông mịn giữ ấm tốt.',
                'description' => 'Xua tan sự ảm đạm của mùa đông bằng những khối màu rực rỡ, tươi mới và giàu năng lượng.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catSweater->id,
                'sku' => 'BS-SW-008',
                'name' => 'Áo Nỉ Nam Có Khóa Cổ Half-Zip Năng Động Phong Cách Thể Thao',
                'slug' => 'ao-ni-nam-khoa-co-half-zip',
                'price' => 390000,
                'original_price' => 510000,
                'stock' => 105,
                'sold_count' => 470,
                'rating' => 4.9,
                'reviews_count' => 74,
                'image' => '/assets/img/products/sweater_08.jpg',
                'colors' => ['Xanh Than Cổ Zip', 'Xám Bạc Cổ Zip'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Khóa kéo kim loại nửa ngực linh hoạt kéo cao chắn gió hoặc mở cổ bẻ phóng khoáng.',
                'description' => 'Item thời trang đa năng được yêu thích trong các buổi dạo phố, chạy bộ hoặc đánh golf mùa lạnh.',
                'is_new' => true,
                'is_featured' => true,
                'is_best_seller' => false,
            ],
            [
                'category_id' => $catSweater->id,
                'sku' => 'BS-HD-009',
                'name' => 'Áo Hoodie Nam Nỉ Chân Cua Phối Túi Bụng Kangaroo Thoải Mái',
                'slug' => 'ao-hoodie-nam-ni-chan-cua-tui-kangaroo',
                'price' => 380000,
                'original_price' => 499000,
                'stock' => 130,
                'sold_count' => 560,
                'rating' => 4.8,
                'reviews_count' => 82,
                'image' => '/assets/img/products/sweater_09.jpg',
                'colors' => ['Đen Tuyển', 'Xám Khói', 'Xanh Rêu'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Vải nỉ chân cua cao cấp không rụng lông ra áo trong, túi bụng sâu rộng để vừa điện thoại ví tiền.',
                'description' => 'Mang lại sự tiện nghi và ấm áp tuyệt đối cho các hoạt động thường ngày trong mùa đông.',
                'is_new' => false,
                'is_featured' => false,
                'is_best_seller' => true,
            ],
            [
                'category_id' => $catSweater->id,
                'sku' => 'BS-SW-010',
                'name' => 'Áo Sweater Nam Dệt Dày Dặn Bo Cổ Bo Gấu Giữ Nhiệt Tối Đa',
                'slug' => 'ao-sweater-nam-det-day-dan-bo-co-bo-gau',
                'price' => 360000,
                'original_price' => 470000,
                'stock' => 140,
                'sold_count' => 630,
                'rating' => 4.9,
                'reviews_count' => 91,
                'image' => '/assets/img/products/sweater_10.jpg',
                'colors' => ['Trắng Ngà', 'Xám Chuột', 'Xanh Rêu Đậm'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'short_description' => 'Đường dệt dày dặn dẻo dai, bo gấu và cổ tay ôm sát ngăn gió lạnh lùa vào cơ thể.',
                'description' => 'Chiếc áo sweater basic tiêu chuẩn đồng hành cùng bạn suốt những tháng ngày đông lạnh giá.',
                'is_new' => true,
                'is_featured' => false,
                'is_best_seller' => false,
            ],
        ];

        $createdProducts = [];
        foreach ($allProductsData as $pData) {
            $pData['status'] = 'active';
            $prod = Product::create($pData);
            $createdProducts[] = $prod;

            // Tạo ảnh trong bảng gallery
            ProductImage::create([
                'product_id' => $prod->id,
                'image_path' => $prod->image,
                'sort_order' => 1,
            ]);
        }

        // 4. COUPONS / VOUCHERS
        Coupon::create([
            'code' => 'BEESTYLE50',
            'title' => 'Giảm 50.000₫ cho đơn hàng áo nam từ 499.000₫',
            'discount_type' => 'fixed',
            'discount_value' => 50000,
            'min_order_value' => 499000,
            'total_limit' => 1000,
            'used_count' => 420,
            'expires_at' => now()->addMonths(6),
            'is_active' => true,
        ]);

        Coupon::create([
            'code' => 'FREESHIPMAX',
            'title' => 'Miễn phí vận chuyển toàn quốc cho đơn từ 300.000₫',
            'discount_type' => 'shipping',
            'discount_value' => 30000,
            'min_order_value' => 300000,
            'total_limit' => 2000,
            'used_count' => 850,
            'expires_at' => now()->addMonths(6),
            'is_active' => true,
        ]);

        Coupon::create([
            'code' => 'VIPBEE15',
            'title' => 'Giảm 15% tổng hóa đơn cho thành viên thân thiết (Tối đa 200k)',
            'discount_type' => 'percent',
            'discount_value' => 15,
            'min_order_value' => 1000000,
            'max_discount_value' => 200000,
            'total_limit' => 500,
            'used_count' => 118,
            'expires_at' => now()->addMonths(3),
            'is_active' => true,
        ]);

        Coupon::create([
            'code' => 'WELCOMEBEE',
            'title' => 'Giảm 30.000₫ cho khách hàng mới mua đơn đầu tiên từ 299.000₫',
            'discount_type' => 'fixed',
            'discount_value' => 30000,
            'min_order_value' => 299000,
            'total_limit' => 5000,
            'used_count' => 1240,
            'expires_at' => now()->addYear(),
            'is_active' => true,
        ]);

        // 5. SAMPLE ORDERS WITH REAL MEN SHIRTS
        $order1 = Order::create([
            'order_code' => 'BEE-20260818-1001',
            'user_id' => $customer1->id,
            'customer_name' => 'Nguyễn Văn Hùng',
            'customer_email' => 'hung.nguyen@gmail.com',
            'customer_phone' => '0912345678',
            'shipping_address' => 'Số 18 Phố Huế, Hoàn Kiếm, Hà Nội',
            'subtotal' => 839000,
            'discount_amount' => 50000,
            'coupon_code' => 'BEESTYLE50',
            'shipping_fee' => 0,
            'total_amount' => 789000,
            'payment_method' => 'cod',
            'payment_status' => 'unpaid',
            'shipping_status' => 'delivered',
            'status_step' => 5,
            'notes' => 'Giao giờ hành chính giúp tôi',
            'created_at' => now()->subDays(3),
        ]);

        OrderItem::create([
            'order_id' => $order1->id,
            'product_id' => $createdProducts[0]->id, // Áo Polo
            'product_name' => $createdProducts[0]->name,
            'product_sku' => $createdProducts[0]->sku,
            'image' => $createdProducts[0]->image,
            'color' => 'Xanh Slate',
            'size' => 'L',
            'price' => $createdProducts[0]->price,
            'quantity' => 1,
            'subtotal' => $createdProducts[0]->price,
        ]);

        OrderItem::create([
            'order_id' => $order1->id,
            'product_id' => $createdProducts[11]->id, // Áo Sơ Mi Trắng
            'product_name' => $createdProducts[11]->name,
            'product_sku' => $createdProducts[11]->sku,
            'image' => $createdProducts[11]->image,
            'color' => 'Trắng Tinh Khôi',
            'size' => '40',
            'price' => $createdProducts[11]->price,
            'quantity' => 1,
            'subtotal' => $createdProducts[11]->price,
        ]);

        $order2 = Order::create([
            'order_code' => 'BEE-20260818-1002',
            'user_id' => $customer2->id,
            'customer_name' => 'Trần Minh Quang',
            'customer_email' => 'quang.tran@gmail.com',
            'customer_phone' => '0934567890',
            'shipping_address' => 'Toà Park 7 Times City, Hai Bà Trưng, Hà Nội',
            'subtotal' => 890000,
            'discount_amount' => 50000,
            'coupon_code' => 'BEESTYLE50',
            'shipping_fee' => 0,
            'total_amount' => 840000,
            'payment_method' => 'vnpay',
            'payment_status' => 'paid',
            'shipping_status' => 'processing',
            'status_step' => 3,
            'notes' => 'Gói quà sinh nhật giúp em',
            'created_at' => now()->subDay(),
        ]);

        OrderItem::create([
            'order_id' => $order2->id,
            'product_id' => $createdProducts[30]->id, // Blazer
            'product_name' => $createdProducts[30]->name,
            'product_sku' => $createdProducts[30]->sku,
            'image' => $createdProducts[30]->image,
            'color' => 'Xanh Kẻ Ca-rô',
            'size' => 'L',
            'price' => $createdProducts[30]->price,
            'quantity' => 1,
            'subtotal' => $createdProducts[30]->price,
        ]);

        // 6. SAMPLE REVIEWS
        Review::create([
            'product_id' => $createdProducts[0]->id,
            'user_id' => $customer1->id,
            'user_name' => $customer1->name,
            'rating' => 5,
            'comment' => 'Áo polo chất vải dệt tổ ong rất xịn xò, mặc đi làm cả ngày không hề bị bí bách hay hôi mùi. 10 điểm cho BeeStyle!',
            'status' => 'approved',
            'created_at' => now()->subDays(2),
        ]);

        Review::create([
            'product_id' => $createdProducts[11]->id,
            'user_id' => $customer2->id,
            'user_name' => $customer2->name,
            'rating' => 5,
            'comment' => 'Sơ mi trắng sợi bamboo mặc mát lịm, giặt máy không bị nhăn nhúm hay gãy cổ. Rất đáng đồng tiền!',
            'status' => 'approved',
            'created_at' => now()->subDay(),
        ]);

        Review::create([
            'product_id' => $createdProducts[30]->id,
            'user_id' => $customer3->id,
            'user_name' => $customer3->name,
            'rating' => 5,
            'comment' => 'Blazer kẻ form rộng chuẩn Hàn Quốc, đệm vai nhẹ tự nhiên mặc rất sang trọng. Đóng gói hộp rất cẩn thận!',
            'status' => 'approved',
            'created_at' => now()->subHours(8),
        ]);
    }
}